# Test Profile Properties
spring.cache.type=none
spring.main.allow-bean-definition-overriding=true
spring.cloud.gcp.logging.enabled=false
spring.cloud.gcp.trace.enabled=false
spring.cloud.gcp.core.enabled=false
